coffee_shop_project:
  outputs:
    dev:
      dbname: coffee_shop
      host: db
      pass: coffee_shop_password
      port: 5432
      schema: dev
      threads: 4
      type: postgres
      user: coffee_shop_user
  target: dev
