coffee_shop_project:
  outputs:
    dev:
      dbname: coffee_shop
      host: "{{ env_var('AIRFLOW_POSTGRES_HOST') }}"
      pass: "{{ env_var('AIRFLOW_POSTGRES_PASSWORD') }}"
      port: 5432
      schema: dev
      threads: 4
      type: postgres
      user: "{{ env_var('AIRFLOW_POSTGRES_USER') }}"
  target: dev
