version: 2

sources:
  - name: dev
    database: coffee_shop
    tables:
      - name: raw_summary_data
        columns:
          - name: id_generals
          - name: file_name
          - name: date_creation
          - name: invoice_id
          - name: currency
          - name: subtotal
          - name: total
          - name: transmitter_id
          - name: transmitter_name
          - name: transmitter_zip_code
          - name: receiver_id
          - name: receiver_name
          - name: invoice_type
          - name: store
          - name: date_insertion

      - name: raw_details_data
        columns:
          - name: id_details
          - name: source
          - name: product_service_key
          - name: product_id
          - name: quantity
          - name: unit_key
          - name: units
          - name: description
          - name: unit_value
          - name: amount
          - name: discount
          - name: amount_object
          - name: date_insertion

      - name: raw_taxes_data
        columns:
          - name: id_taxes
          - name: source
          - name: base
          - name: amount
          - name: tax_id
          - name: type_factor
          - name: rate_or_share
          - name: date_insertion
      
      - name: raw_sales_data
        columns:
          - name: id_sales
          - name: sales_date
          - name: devolutions
          - name: sales_cash
          - name: sales_debit
          - name: sales_credit
          - name: sales_uber
          - name: sales_rappi
          - name: sales_transfer
          - name: num_tickets
          - name: avg_tickets
          - name: num_devolutions
          - name: total_devolutions
          - name: num_invitations
          - name: total_invitations
          - name: base_tax_16
          - name: amount_tax_16
          - name: base_tax_0
          - name: amount_tax_0
          - name: total_bases
          - name: total_taxes
          - name: total
          - name: total_cards